### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by runepiper** [sponsorware/recipe#1]
What about licensing? Using the MIT license or similar while the code is not public, is not suitable is it? Some could upload the code before the threshold is crossed.

**Comment by stefanbuck** [comment]
Great question. As far as I know, if no license is given, the copyright law of your country apply unchanged ... whatever this means in detail. Maybe best to add a short disclaimer which says something along those lines:

> By granting access to this repo you agree to not distribute or make profit from this source code.

Although `distribute` is tricky, because even hosting it yourself is already some kind of distribution.

**Comment by runepiper** [comment]
Sounds reasonable to me.

**Comment by pkoch** [comment]
I think we're sweeping an important topic under the rug. It'd be ideal to have some standard licensing agreement (even if it has to be per country), pre-vetted by a team of competent lawyers, that people can choose from on a pre-release period.

The less people have to think about navigating this maze, the more time they'll have to write code, the more sponsorware we'll have.

**Comment by ferki** [comment]
There's probably no "one size fits all" solution, as the license details all depend on the project in question, and the author's intent with their end result of creative work. Therefore I'd approach it from the same angle like any other licensing question for new projects: what's my intent with the product as author, what activities I allow or disallow for anyone who obtains a copy, and under what conditions.

For anything custom like a sponsorware license, I probably would start with taking a well-known and proven license like MIT, and modify it _slightly_, _if needed_. Of course, the less modifications I would need to do, the better it is. And this all depends on what I, as an author and copyright holder, see best fit for the project. 

For example, I could decide to leave "use, copy, modify" in as allowed, and take "merge, publish, distribute, sublicense, and/or sell copies" out as disallowed. The condition could be the same: "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software".

I am not a lawyer, but the above could be an idea to start with, before presenting the case to an actual lawyer.
